language: go
go:
- 1.6
install:
- npm install
- sh install-hugo.sh
- cp node_modules/sharebutton/dist/share-button.min.js static/javascripts/share-button.js
- cp now.json public/
script:
- ./hugo
after_success:
- (cd public/ && now --token $NOW_TOKEN)
- (cd public/ && now alias --token $NOW_TOKEN)
addons:
  ssh_known_hosts:
  - github.com
  - 192.30.253.112
  - 192.30.253.113
sudo: false
branches:
  only:
  - master